spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.209.96.12:51130/bumpy
    username: "bumpyapp"
    password: "@bumpy123!"

cors:
  origins:
    - "*"

springfox:
  documentation:
    enabled: false