spring:
  profiles:
    active: local
  # Swagger 3.0 설정을 위한 추가설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.209.96.12:51130/bumpy
    username: "bumpyapp"
    password: "@bumpy123!"

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        format_sql: true

caching:
  evictTTL: 43200000

server:
  servlet:
    context-path: /api
  port: 8090

file:
  upload:
    path: c:/uploadFiles/

cors:
  origins:
    - "*"

logging:
  config: classpath:log4j2.yml