spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria-db:51130/bumpy
    username: "bumpyapp"
    password:

#  jpa:
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
#    open-in-view: false

file:
  upload:
    path: /uploadFiles/

#cors:
#  origins:
#    - "www.bumpy.co.kr"

springfox:
  documentation:
    enabled: false