spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.34.143.244:33056/bumpy
    username: "bumpyapp"
    password: "@bumpy123!"

cookie:
  domain: www.bumpy.co.kr