spring:
  profiles:
    active: local
  # Swagger 3.0 설정을 위한 추가설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.34.143.244:33056/bumpy
    username: "bumpyapp"
    password: "@bumpy123!"

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /api
  port: 8090

logging:
  config: classpath:log4j2.yml

jwt:
  private:
    key: classpath:rsa.private.key
  public:
    key: classpath:rsa.public.key