spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://13.209.96.12:51130/bumpy
    username: "bumpyapp"
    password: "@bumpy123!"

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false


cors:
  origins:
    - "*"

springfox:
  documentation:
    enabled: false