pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // GitHub 프로젝트 클론 및 백엔드 브랜치로 전환
                checkout([$class: 'GitSCM', branches: [[name: 'backend']],
                          doGenerateSubmoduleConfigurations: false,
                          submoduleCfg: [],
                          userRemoteConfigs: [[credentialsId: 'Patabear', url: 'git@github.com:JuneHyung/Bumpy.git']]])
            }
        }

        stage('Build') {
            steps {
                // Gradle을 사용하여 프로젝트 빌드
                dir('develop/backend') {
                    sh 'chmod +x gradlew'
                    sh './gradlew build'
                }
            }
        }

        stage('Copy Files to Remote Server') {
            steps {
                // 빌드된 파일을 원격 서버로 복사
                dir('develop/backend/build/libs') {
                    sshagent(credentials: ['server1ssh']) {
                        sh 'ssh server1@172.30.1.50 "cp /home/server1/jenkins/jenkins_home/workspace/bumpy-back/develop/backend/build/libs/* /home/server1/bumpy/jar/"'
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                // 원격 서버에서 Docker Compose 실행
                sshagent(credentials: ['server1ssh']) {
                    sh 'ssh server1@172.30.1.50 "cd /home/server1/bumpy && docker-compose down && docker-compose up -d --build"'
                }
            }
        }
        // 필요한 추가 단계를 여기에 추가할 수 있습니다.
    }
}
